---
pagetitle: Edges
---

```{r, eval=TRUE, echo = FALSE}
require("visNetwork", quietly = TRUE)
```

## Individual configuration

* Adding more variables on edges data.frame. See **visEdges** for available options.

```{r}
edges <- data.frame(from = sample(1:10,8), to = sample(1:10, 8),
                    
  # add labels on edges                  
  label = paste("Edge", 1:8),
  
  # length
  length = c(100,500),
  
  # arrows
  arrows = c("to", "from", "middle", "middle;to"),
  
  # dashes
  dashes = c(TRUE, FALSE),
  
  # tooltip (html or character)
  title = paste("Edge", 1:8),
  
  # smooth
  smooth = c(FALSE, TRUE),
  
  # shadow
  shadow = c(FALSE, TRUE, FALSE, TRUE)) 

# head(edges)
#  from to  label length    arrows dashes  title smooth shadow
#    10  7 Edge 1    100        to   TRUE Edge 1  FALSE  FALSE
#     4 10 Edge 2    500      from  FALSE Edge 2   TRUE   TRUE

nodes <- data.frame(id = 1:10, group = c("A", "B"))
```

```{r}
visNetwork(nodes, edges, height = "500px", width = "100%")
```

## Global configuration

* Set global options for edges using directly **visEdges** function :

```{r}
nodes <- data.frame(id = 1:4)
edges <- data.frame(from = c(2,4,3,2), to = c(1,2,4,3))

visNetwork(nodes, edges, width = "100%") %>% 
  visEdges(shadow = TRUE,
           arrows =list(to = list(enabled = TRUE, scaleFactor = 2)),
           color = list(color = "lightblue", highlight = "red"))           
```

* You can also combine individual and global options : 

```{r}
nodes <- data.frame(id = 1:4, label = 1:4)
edges <- data.frame(from = c(2,4,3,2), to = c(1,2,4,3), 
                    dashes = c(TRUE, FALSE))

visNetwork(nodes, edges, width = "100%") %>% 
  visEdges(shadow = TRUE,
           arrows =list(to = list(enabled = TRUE, scaleFactor = 2)),
           color = list(color = "lightblue", highlight = "red"))             
```