---
pagetitle: Interactions
---

```{r, eval=TRUE, echo = FALSE}
require("visNetwork", quietly = TRUE)
```

It's possible to configure the network interaction with **visInteraction()** :

```{r, echo=FALSE}
nb <- 10
nodes <- data.frame(id = 1:nb, label = paste("Label", 1:nb),
 group = sample(LETTERS[1:3], nb, replace = TRUE), value = 1:nb,
 title = paste0("<p>", 1:nb,"<br>Tooltip !</p>"), stringsAsFactors = FALSE)

edges <- data.frame(from = trunc(runif(nb)*(nb-1))+1,
 to = trunc(runif(nb)*(nb-1))+1,
 value = rnorm(nb, 10), label = paste("Edge", 1:nb),
 title = paste0("<p>", 1:nb,"<br>Edge Tooltip !</p>"))
```


## Frozen network

Using *dragNodes*, *dragView*, and *zoomView* :

```{r}
visNetwork(nodes, edges, height = "500px", width = "100%") %>% 
  visInteraction(dragNodes = FALSE, dragView = FALSE, zoomView = FALSE)
```

## Hide edges/nodes on drag

Using *hideEdgesOnDrag*, and *hideNodesOnDrag* : 

```{r}
visNetwork(nodes, edges, height = "500px", width = "100%") %>% 
  visInteraction(hideEdgesOnDrag = TRUE)
```

## Navigation buttons

We can navigation buttons with *navigationButtons* :

```{r}
visNetwork(nodes, edges, height = "500px", width = "100%") %>% 
  visInteraction(navigationButtons = TRUE)
```
