---
pagetitle: Introduction
---

## Introduction

**rAmCharts** is an R package for interactive charts. It is based on the javascript library **amcharts.js** (https://amcharts.com). Currently it implements most of the functionnalities found in the distributions **CHARTS** and **STOCK CHARTS**. You'll find the source code and bug reports on our [github page](https://github.com/DataKnowledge/rAmCharts.), do not hesitate to send your bugs and you comments.

Based on [htmlwidgets](http://www.htmlwidgets.org/), it is compatible with [shiny ](http://shiny.rstudio.com/),  R Markdown documents and RStudio viewer.

## Prerequisite

It uses internally the package **pipeR** which is usefull to draw complex charts by keeping a certain level of readability in the code. The function mainly used is `%>>%` (or `pipeline()`) but the package allow to do many more, see the official tutorial 

## Installation

Package is now available on CRAN.

```{r, eval=FALSE}
install.packages("rAmCharts")

# can have new features in developpement version 
devtools::install_github("dataknowledge/rAmCharts")
```

## How it's works ?
C'est Jeffery!

github_page :[]



